### ISSUE TITLE
PDB file repostirory over http should not use ftp.wwpdb.org DNS name

### ISSUE THREAD

**Issue by josemduarte** [rcsb/py-rcsb_utils_repository#13]
Instead of `https://ftp.wwpdb.org` it should be `https://files.wwpdb.org`. See [announcement](http://www.wwpdb.org/news/news?year=2022#6303be3b707ecd4f63b3d3d9)

This file contains some references to the bad DNS name:

https://github.com/rcsb/py-rcsb_utils_repository/blob/b1b16b5d206b3e74e7d8bdefb0138d0146ea440e/rcsb/utils/repository/CurrentHoldingsProvider.py#L2

But there might be others in the repo. I didn't check.

**Comment by piehld** [comment]
Thanks for pointing out, @josemduarte!
